PUBLIC_PACKET_AUTHORITY_TERMS = {
    "packet_id",
    "revision_id",
    "content_hash",
    "decision_lock",
    "decision_lock_before",
    "decision_lock_after",
    "derived_from_packet_id",
    "evidence_receipt_id",
    "evidence_receipt_ids",
    "snapshot_content_hash",
    "snapshot_revision_id",
}


FORBIDDEN_PRIVATE_V1_TERMS = [
    "ask_ia",
    "living_document",
    "advanced_workspace",
    "mcp_agent_tool_access",
    "coding_spend",
    "production_ai",
    "gpu_api",
    "route_evidence",
    "approval_watch_lane",
    "WorkloadProfile",
    "FactPack",
    "ArtifactProjection",
    "user_problem",
    "decision_title",
    "facts_captured",
    "proof_used",
    "candidate_paths",
    "missing_truths",
    "approval_step",
    "must_show",
    "must_not_show",
    "ia_chat_packet_native_controller",
]
